# Generated by Django 6.0.4 on 2026-04-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='es_mensual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicios',
            name='icono',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
